version: '2'
services:
  db:
    build: ./db
    restart: always
    ports:
      - '3307:3306'
    volumes:
      - task_db:/var/lib/mysql 
    hostname: mysql-local-db
    networks:
      - task_network
  login:
    build: ./serv3
    ports:
      - '9001:5000'
    depends_on: 
      - db
    hostname: login.local
    networks:
      task_network:
        aliases:
          - login.local
  tasks:
    build: ./serv4
    ports:
      - '9002:5000'
    depends_on:
      - db
      - login
    hostname: tasks.local
    networks:
      task_network:
        aliases:
          - tasks.local
networks:
  task_network:

volumes:
  task_db: